FROM node:18

WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./

# Install dependencies with the appropriate package manager
RUN  npm install

COPY . .

EXPOSE 3000

# Start Next.js in development mode
CMD ["npm", "run", "dev"] 
