services:
  python:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    networks:
      - my-network
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network
    depends_on:
      - python
  cron-tests:
    build:
      context: ./cronjob
      dockerfile: Dockerfile
    networks:
      - my-network
    depends_on:
      - nextjs

networks:
  my-network:
