version: "3.8"

services:
  nextjs:
    build:
      context: ./nextjs-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

  python:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "6969:6969"
    networks:
      - my-network

networks:
  my-network:
