version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "6969:6969"
    networks:
      - gg-network
    volumes:
      - ./backend:/app
      - ./backend/docs:/app/docs:ro
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    restart: unless-stopped
    
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    networks:
      - gg-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

networks:
  gg-network:
    driver: bridge
