name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Debug Environment
        run: |
          echo "HOST is set to: ${{ secrets.HOST || vars.HOST }}"
          echo "SSH_PRIVATE_KEY is set: ${{ secrets.SSH_PRIVATE_KEY != '' }}"
      
      - name: Deploy to Homelab via Cloudflare
        uses: npgy/cloudflared-ssh-action@v2.0
        with:
          host: ${{ secrets.HOST || vars.HOST }}
          username: root
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          commands: |
            cd /Sites/jenkins-rspec-test-difference
            touch yes.txt
            # git checkout main &&
            # git pull origin main &&
            # docker compose build && docker compose up -d